### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by sand050965**
Hi Peng!

this is 楊仙宇, I've done the assignment this week ~

and I also did some adjustments for last week assignment,  for redesigning the database

**here are my url:

http://54.249.243.14:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout issues: borders, margins, and aspect ratio of images should keep the same as original one.

**Comment by sand050965** [comment]
Hi Peng!

I just made some modifications on css file to fix the issue.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout issues: borders, margins as shown above.

**Comment by sand050965** [comment]
Hi Peng!

Just modified borders and margins for the layout issues~

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
