### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by sand050965**
name: 楊仙宇

哈囉~~彭彭，要再麻煩老師協助進行code review了，謝謝！

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. we should setup protection rule for `main` branch.
2. paste your live URLs for testing.

**Comment by sand050965** [comment]
1.HI~彭彭，抱歉，剛剛已修正將main分支設定保護機制

2.Here are my live URLs for testing:
http://54.249.243.14:3000/api/attractions?page=1
http://54.249.243.14:3000/api/attractions?page=0&keyword=藝文館所
http://54.249.243.14:3000/api/attractions?page=0&keyword=北
http://54.249.243.14:3000/api/attraction/10

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Comment by sand050965** [comment]
Hi Peng~ I've already launched the Re-request review, thanks for reminding me.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done but there is redundant `null` value in the response of http://54.249.243.14:3000/api/categories

**Comment by sand050965** [comment]
Hi Peng~ Just deleted it from the table !
I inserted the null value into table on pupose, since there are a null value in mrt column, and I wasn't pretty sure whether there was a same situation in category column at that time.
But anyway, thanks for pointing out the redunduncy for me : )

**Review by cwpeng — APPROVED** [review]
Good. Well Done. :)

Thanks for your explanation. In the future, if we did find out there exists `null` value in category, I will give you credit for this.

**Pull request merged**
